package com.eleapp.dao;

import com.eleapp.model.Appinfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface AppinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer autoID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbggenerated
     */
    int insert(Appinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbggenerated
     */
    int insertSelective(Appinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbggenerated
     */
    Appinfo selectByPrimaryKey(Integer autoID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Appinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Appinfo record);


    List<Map> selectAllAppList(Map param);

    int updateAppStatus(@Param("status")String status,@Param("id")String id);

    int setPerfact(@Param("appIds")String appIds,@Param("perfact")Integer perfact);
}