package com.eleapp.dao;

import com.eleapp.model.Apptypeinfo;

public interface ApptypeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptypeinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer autoID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptypeinfo
     *
     * @mbggenerated
     */
    int insert(Apptypeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptypeinfo
     *
     * @mbggenerated
     */
    int insertSelective(Apptypeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptypeinfo
     *
     * @mbggenerated
     */
    Apptypeinfo selectByPrimaryKey(Integer autoID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptypeinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Apptypeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apptypeinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Apptypeinfo record);
}