package com.eleapp.dao;

import com.eleapp.model.EleApptotype;

public interface EleApptotypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_apptotype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_apptotype
     *
     * @mbggenerated
     */
    int insert(EleApptotype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_apptotype
     *
     * @mbggenerated
     */
    int insertSelective(EleApptotype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_apptotype
     *
     * @mbggenerated
     */
    EleApptotype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_apptotype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EleApptotype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_apptotype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EleApptotype record);
}