package com.eleapp.dao;

import com.eleapp.model.EleAppImages;

public interface EleAppImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_app_images
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_app_images
     *
     * @mbggenerated
     */
    int insert(EleAppImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_app_images
     *
     * @mbggenerated
     */
    int insertSelective(EleAppImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_app_images
     *
     * @mbggenerated
     */
    EleAppImages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_app_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EleAppImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_app_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EleAppImages record);
}