package com.eleapp.dao;

import com.eleapp.model.EleApp;

import java.util.List;

public interface EleAppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_app
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_app
     *
     * @mbggenerated
     */
    int insert(EleApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_app
     *
     * @mbggenerated
     */
    int insertSelective(EleApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_app
     *
     * @mbggenerated
     */
    EleApp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_app
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EleApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_app
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EleApp record);

    List<EleApp> selectAllAppList();
}