package com.eleapp.dao;

import com.eleapp.model.EleCompany;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface EleCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_company
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_company
     *
     * @mbggenerated
     */
    int insert(EleCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_company
     *
     * @mbggenerated
     */
    int insertSelective(EleCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_company
     *
     * @mbggenerated
     */
    EleCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EleCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EleCompany record);

    List<Map> selectAllCompList(Map param);

    int updateCompStatus(@Param("status")String status,@Param("id")String id);
}