package com.eleapp.dao;

import com.eleapp.model.EleClass;

import java.util.List;
import java.util.Map;

public interface EleClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_class
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_class
     *
     * @mbggenerated
     */
    int insert(EleClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_class
     *
     * @mbggenerated
     */
    int insertSelective(EleClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_class
     *
     * @mbggenerated
     */
    EleClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_class
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EleClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_class
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EleClass record);

    List<Map> selectAllClassList(Map param);
}