package com.eleapp.dao;

import com.eleapp.model.EleNews;

import java.util.List;

public interface EleNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_news
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_news
     *
     * @mbggenerated
     */
    int insert(EleNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_news
     *
     * @mbggenerated
     */
    int insertSelective(EleNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_news
     *
     * @mbggenerated
     */
    EleNews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EleNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(EleNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EleNews record);

    List<EleNews> selectAllNewsList();
}