package com.eleapp.dao;

import com.eleapp.model.EleRbacOrganization;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface EleRbacOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_rbac_organization
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_rbac_organization
     *
     * @mbggenerated
     */
    int insert(EleRbacOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_rbac_organization
     *
     * @mbggenerated
     */
    int insertSelective(EleRbacOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_rbac_organization
     *
     * @mbggenerated
     */
    EleRbacOrganization selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_rbac_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EleRbacOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_rbac_organization
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EleRbacOrganization record);

    List<Map> getOrgListByOrgId(@Param("orgId")String orgId);

    List<Map> getRuralListByOrgId(@Param("orgId")String orgId);

}