package com.eleapp.dao;

import com.eleapp.model.EleSchool;

import java.util.List;
import java.util.Map;

public interface EleSchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_school
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_school
     *
     * @mbggenerated
     */
    int insert(EleSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_school
     *
     * @mbggenerated
     */
    int insertSelective(EleSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_school
     *
     * @mbggenerated
     */
    EleSchool selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_school
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EleSchool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_school
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EleSchool record);

    List<Map> selectAllSchoolList(Map param);
}