package com.eleapp.dao;

import com.eleapp.model.EleTeacher;

import java.util.List;
import java.util.Map;

public interface EleTeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_teacher
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_teacher
     *
     * @mbggenerated
     */
    int insert(EleTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_teacher
     *
     * @mbggenerated
     */
    int insertSelective(EleTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_teacher
     *
     * @mbggenerated
     */
    EleTeacher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_teacher
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EleTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ele_teacher
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EleTeacher record);

    List<Map> selectAllTeacherList(Map param);
}