package com.eleapp.dao;

import com.eleapp.model.Newsinfo;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface NewsinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer autoID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsinfo
     *
     * @mbggenerated
     */
    int insert(Newsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsinfo
     *
     * @mbggenerated
     */
    int insertSelective(Newsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsinfo
     *
     * @mbggenerated
     */
    Newsinfo selectByPrimaryKey(Integer autoID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Newsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Newsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Newsinfo record);

    List<Newsinfo> selectAllNewsList(Map  param);
}