package com.eleapp.dao;

import com.eleapp.model.SysRbacDataaccess;

public interface SysRbacDataaccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_dataaccess
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_dataaccess
     *
     * @mbggenerated
     */
    int insert(SysRbacDataaccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_dataaccess
     *
     * @mbggenerated
     */
    int insertSelective(SysRbacDataaccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_dataaccess
     *
     * @mbggenerated
     */
    SysRbacDataaccess selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_dataaccess
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRbacDataaccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_dataaccess
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRbacDataaccess record);

    SysRbacDataaccess selectByUserId(Integer userId);
}