package com.eleapp.dao;

import com.eleapp.model.SysRbacMenu;
import com.eleapp.model.SysRbacTopMenuDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysRbacMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_menu
     *
     * @mbggenerated
     */
    int insert(SysRbacMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_menu
     *
     * @mbggenerated
     */
    int insertSelective(SysRbacMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_menu
     *
     * @mbggenerated
     */
    SysRbacMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRbacMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRbacMenu record);

    List<SysRbacTopMenuDO> queyRoleMenuNew(@Param("roleId") String roleId,@Param("menuId") String menuId);
}