package com.eleapp.dao;

import com.eleapp.model.SysRbacRoleauth;
import org.apache.ibatis.annotations.Param;

public interface SysRbacRoleauthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_roleauth
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_roleauth
     *
     * @mbggenerated
     */
    int insert(SysRbacRoleauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_roleauth
     *
     * @mbggenerated
     */
    int insertSelective(SysRbacRoleauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_roleauth
     *
     * @mbggenerated
     */
    SysRbacRoleauth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_roleauth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRbacRoleauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rbac_roleauth
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRbacRoleauth record);

    SysRbacRoleauth selectByRoleIdMenuId(@Param("roleId")Integer roleId, @Param("menuId")Integer menuId);

    int deleteByRoleIdMenuId(@Param("menuId")Integer menuId,@Param("roleId")Integer roleId);

    int deleteByRoleId(@Param("roleId") Integer roleId);
}