package com.eleapp.model;

import java.util.Date;

public class Appinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.AutoID
     *
     * @mbggenerated
     */
    private Integer autoID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.AppCode
     *
     * @mbggenerated
     */
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.AppName
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.AppExplain
     *
     * @mbggenerated
     */
    private String appExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.AppType
     *
     * @mbggenerated
     */
    private Integer appType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.CompanyCode
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.AppAddress
     *
     * @mbggenerated
     */
    private String appAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.AppSize
     *
     * @mbggenerated
     */
    private Double appSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.ImgSmall
     *
     * @mbggenerated
     */
    private String imgSmall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.ImgBig
     *
     * @mbggenerated
     */
    private String imgBig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.IsFree
     *
     * @mbggenerated
     */
    private Integer isFree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.Price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.OperaterUserID
     *
     * @mbggenerated
     */
    private String operaterUserID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.Status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.LastReviewDate
     *
     * @mbggenerated
     */
    private Date lastReviewDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.UploadUserID
     *
     * @mbggenerated
     */
    private Integer uploadUserID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.UploadExplain
     *
     * @mbggenerated
     */
    private String uploadExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.CreateDate
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appinfo.ModifyDate
     *
     * @mbggenerated
     */
    private String modifyDate;


    private Integer IsDel;

    public Integer getIsDel() {
        return IsDel;
    }

    public void setIsDel(Integer isDel) {
        IsDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.AutoID
     *
     * @return the value of appinfo.AutoID
     *
     * @mbggenerated
     */
    public Integer getAutoID() {
        return autoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.AutoID
     *
     * @param autoID the value for appinfo.AutoID
     *
     * @mbggenerated
     */
    public void setAutoID(Integer autoID) {
        this.autoID = autoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.AppCode
     *
     * @return the value of appinfo.AppCode
     *
     * @mbggenerated
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.AppCode
     *
     * @param appCode the value for appinfo.AppCode
     *
     * @mbggenerated
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.AppName
     *
     * @return the value of appinfo.AppName
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.AppName
     *
     * @param appName the value for appinfo.AppName
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.AppExplain
     *
     * @return the value of appinfo.AppExplain
     *
     * @mbggenerated
     */
    public String getAppExplain() {
        return appExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.AppExplain
     *
     * @param appExplain the value for appinfo.AppExplain
     *
     * @mbggenerated
     */
    public void setAppExplain(String appExplain) {
        this.appExplain = appExplain == null ? null : appExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.AppType
     *
     * @return the value of appinfo.AppType
     *
     * @mbggenerated
     */
    public Integer getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.AppType
     *
     * @param appType the value for appinfo.AppType
     *
     * @mbggenerated
     */
    public void setAppType(Integer appType) {
        this.appType = appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.CompanyCode
     *
     * @return the value of appinfo.CompanyCode
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.CompanyCode
     *
     * @param companyCode the value for appinfo.CompanyCode
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.AppAddress
     *
     * @return the value of appinfo.AppAddress
     *
     * @mbggenerated
     */
    public String getAppAddress() {
        return appAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.AppAddress
     *
     * @param appAddress the value for appinfo.AppAddress
     *
     * @mbggenerated
     */
    public void setAppAddress(String appAddress) {
        this.appAddress = appAddress == null ? null : appAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.AppSize
     *
     * @return the value of appinfo.AppSize
     *
     * @mbggenerated
     */
    public Double getAppSize() {
        return appSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.AppSize
     *
     * @param appSize the value for appinfo.AppSize
     *
     * @mbggenerated
     */
    public void setAppSize(Double appSize) {
        this.appSize = appSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.ImgSmall
     *
     * @return the value of appinfo.ImgSmall
     *
     * @mbggenerated
     */
    public String getImgSmall() {
        return imgSmall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.ImgSmall
     *
     * @param imgSmall the value for appinfo.ImgSmall
     *
     * @mbggenerated
     */
    public void setImgSmall(String imgSmall) {
        this.imgSmall = imgSmall == null ? null : imgSmall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.ImgBig
     *
     * @return the value of appinfo.ImgBig
     *
     * @mbggenerated
     */
    public String getImgBig() {
        return imgBig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.ImgBig
     *
     * @param imgBig the value for appinfo.ImgBig
     *
     * @mbggenerated
     */
    public void setImgBig(String imgBig) {
        this.imgBig = imgBig == null ? null : imgBig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.IsFree
     *
     * @return the value of appinfo.IsFree
     *
     * @mbggenerated
     */
    public Integer getIsFree() {
        return isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.IsFree
     *
     * @param isFree the value for appinfo.IsFree
     *
     * @mbggenerated
     */
    public void setIsFree(Integer isFree) {
        this.isFree = isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.Price
     *
     * @return the value of appinfo.Price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.Price
     *
     * @param price the value for appinfo.Price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.OperaterUserID
     *
     * @return the value of appinfo.OperaterUserID
     *
     * @mbggenerated
     */
    public String getOperaterUserID() {
        return operaterUserID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.OperaterUserID
     *
     * @param operaterUserID the value for appinfo.OperaterUserID
     *
     * @mbggenerated
     */
    public void setOperaterUserID(String operaterUserID) {
        this.operaterUserID = operaterUserID == null ? null : operaterUserID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.Status
     *
     * @return the value of appinfo.Status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.Status
     *
     * @param status the value for appinfo.Status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.LastReviewDate
     *
     * @return the value of appinfo.LastReviewDate
     *
     * @mbggenerated
     */
    public Date getLastReviewDate() {
        return lastReviewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.LastReviewDate
     *
     * @param lastReviewDate the value for appinfo.LastReviewDate
     *
     * @mbggenerated
     */
    public void setLastReviewDate(Date lastReviewDate) {
        this.lastReviewDate = lastReviewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.UploadUserID
     *
     * @return the value of appinfo.UploadUserID
     *
     * @mbggenerated
     */
    public Integer getUploadUserID() {
        return uploadUserID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.UploadUserID
     *
     * @param uploadUserID the value for appinfo.UploadUserID
     *
     * @mbggenerated
     */
    public void setUploadUserID(Integer uploadUserID) {
        this.uploadUserID = uploadUserID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.UploadExplain
     *
     * @return the value of appinfo.UploadExplain
     *
     * @mbggenerated
     */
    public String getUploadExplain() {
        return uploadExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.UploadExplain
     *
     * @param uploadExplain the value for appinfo.UploadExplain
     *
     * @mbggenerated
     */
    public void setUploadExplain(String uploadExplain) {
        this.uploadExplain = uploadExplain == null ? null : uploadExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.CreateDate
     *
     * @return the value of appinfo.CreateDate
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.CreateDate
     *
     * @param createDate the value for appinfo.CreateDate
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appinfo.ModifyDate
     *
     * @return the value of appinfo.ModifyDate
     *
     * @mbggenerated
     */
    public String getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appinfo.ModifyDate
     *
     * @param modifyDate the value for appinfo.ModifyDate
     *
     * @mbggenerated
     */
    public void setModifyDate(String modifyDate) {
        this.modifyDate = modifyDate == null ? null : modifyDate.trim();
    }
}