package com.eleapp.model;

import java.util.Date;

public class Apptypeinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptypeinfo.AutoID
     *
     * @mbggenerated
     */
    private Integer autoID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptypeinfo.AppTypeName
     *
     * @mbggenerated
     */
    private String appTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptypeinfo.AppTypeCode
     *
     * @mbggenerated
     */
    private String appTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptypeinfo.AppTypeExplain
     *
     * @mbggenerated
     */
    private String appTypeExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptypeinfo.TypeRuleAutoID
     *
     * @mbggenerated
     */
    private Integer typeRuleAutoID;

    public Integer getAppInfo_AutoID() {
        return appInfo_AutoID;
    }

    public void setAppInfo_AutoID(Integer appInfo_AutoID) {
        this.appInfo_AutoID = appInfo_AutoID;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptypeinfo.AppInfo_Auto ID
     *
     * @mbggenerated
     */
    private Integer appInfo_AutoID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptypeinfo.TypeRuleConf_AutoID
     *
     * @mbggenerated
     */
    private Integer typeRuleConf_AutoID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptypeinfo.CreateDate
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptypeinfo.ModifyDate
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apptypeinfo.Status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptypeinfo.AutoID
     *
     * @return the value of apptypeinfo.AutoID
     *
     * @mbggenerated
     */
    public Integer getAutoID() {
        return autoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptypeinfo.AutoID
     *
     * @param autoID the value for apptypeinfo.AutoID
     *
     * @mbggenerated
     */
    public void setAutoID(Integer autoID) {
        this.autoID = autoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptypeinfo.AppTypeName
     *
     * @return the value of apptypeinfo.AppTypeName
     *
     * @mbggenerated
     */
    public String getAppTypeName() {
        return appTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptypeinfo.AppTypeName
     *
     * @param appTypeName the value for apptypeinfo.AppTypeName
     *
     * @mbggenerated
     */
    public void setAppTypeName(String appTypeName) {
        this.appTypeName = appTypeName == null ? null : appTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptypeinfo.AppTypeCode
     *
     * @return the value of apptypeinfo.AppTypeCode
     *
     * @mbggenerated
     */
    public String getAppTypeCode() {
        return appTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptypeinfo.AppTypeCode
     *
     * @param appTypeCode the value for apptypeinfo.AppTypeCode
     *
     * @mbggenerated
     */
    public void setAppTypeCode(String appTypeCode) {
        this.appTypeCode = appTypeCode == null ? null : appTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptypeinfo.AppTypeExplain
     *
     * @return the value of apptypeinfo.AppTypeExplain
     *
     * @mbggenerated
     */
    public String getAppTypeExplain() {
        return appTypeExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptypeinfo.AppTypeExplain
     *
     * @param appTypeExplain the value for apptypeinfo.AppTypeExplain
     *
     * @mbggenerated
     */
    public void setAppTypeExplain(String appTypeExplain) {
        this.appTypeExplain = appTypeExplain == null ? null : appTypeExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptypeinfo.TypeRuleAutoID
     *
     * @return the value of apptypeinfo.TypeRuleAutoID
     *
     * @mbggenerated
     */
    public Integer getTypeRuleAutoID() {
        return typeRuleAutoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptypeinfo.TypeRuleAutoID
     *
     * @param typeRuleAutoID the value for apptypeinfo.TypeRuleAutoID
     *
     * @mbggenerated
     */
    public void setTypeRuleAutoID(Integer typeRuleAutoID) {
        this.typeRuleAutoID = typeRuleAutoID;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptypeinfo.TypeRuleConf_AutoID
     *
     * @return the value of apptypeinfo.TypeRuleConf_AutoID
     *
     * @mbggenerated
     */
    public Integer getTypeRuleConf_AutoID() {
        return typeRuleConf_AutoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptypeinfo.TypeRuleConf_AutoID
     *
     * @param typeRuleConf_AutoID the value for apptypeinfo.TypeRuleConf_AutoID
     *
     * @mbggenerated
     */
    public void setTypeRuleConf_AutoID(Integer typeRuleConf_AutoID) {
        this.typeRuleConf_AutoID = typeRuleConf_AutoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptypeinfo.CreateDate
     *
     * @return the value of apptypeinfo.CreateDate
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptypeinfo.CreateDate
     *
     * @param createDate the value for apptypeinfo.CreateDate
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptypeinfo.ModifyDate
     *
     * @return the value of apptypeinfo.ModifyDate
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptypeinfo.ModifyDate
     *
     * @param modifyDate the value for apptypeinfo.ModifyDate
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apptypeinfo.Status
     *
     * @return the value of apptypeinfo.Status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apptypeinfo.Status
     *
     * @param status the value for apptypeinfo.Status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}