package com.eleapp.model;

import java.util.Date;

public class EleApptotype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_apptotype.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_apptotype.appTypeId
     *
     * @mbggenerated
     */
    private Integer appTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_apptotype.appId
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_apptotype.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_apptotype.motifyTime
     *
     * @mbggenerated
     */
    private Date motifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_apptotype.isDel
     *
     * @mbggenerated
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_apptotype.id
     *
     * @return the value of ele_apptotype.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_apptotype.id
     *
     * @param id the value for ele_apptotype.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_apptotype.appTypeId
     *
     * @return the value of ele_apptotype.appTypeId
     *
     * @mbggenerated
     */
    public Integer getAppTypeId() {
        return appTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_apptotype.appTypeId
     *
     * @param appTypeId the value for ele_apptotype.appTypeId
     *
     * @mbggenerated
     */
    public void setAppTypeId(Integer appTypeId) {
        this.appTypeId = appTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_apptotype.appId
     *
     * @return the value of ele_apptotype.appId
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_apptotype.appId
     *
     * @param appId the value for ele_apptotype.appId
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_apptotype.createTime
     *
     * @return the value of ele_apptotype.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_apptotype.createTime
     *
     * @param createTime the value for ele_apptotype.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_apptotype.motifyTime
     *
     * @return the value of ele_apptotype.motifyTime
     *
     * @mbggenerated
     */
    public Date getMotifyTime() {
        return motifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_apptotype.motifyTime
     *
     * @param motifyTime the value for ele_apptotype.motifyTime
     *
     * @mbggenerated
     */
    public void setMotifyTime(Date motifyTime) {
        this.motifyTime = motifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_apptotype.isDel
     *
     * @return the value of ele_apptotype.isDel
     *
     * @mbggenerated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_apptotype.isDel
     *
     * @param isDel the value for ele_apptotype.isDel
     *
     * @mbggenerated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}