package com.eleapp.model;

import java.util.Date;

public class EleApp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_app.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_app.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_app.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_app.imgUrl
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_app.appUrl
     *
     * @mbggenerated
     */
    private String appUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_app.auditing
     *
     * @mbggenerated
     */
    private Integer auditing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_app.auditUserId
     *
     * @mbggenerated
     */
    private Integer auditUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_app.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_app.mofifor
     *
     * @mbggenerated
     */
    private Integer mofifor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_app.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_app.motifyTime
     *
     * @mbggenerated
     */
    private Date motifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_app.isDel
     *
     * @mbggenerated
     */
    private Integer isDel;

    private Date auditDate;

    public String getCompanyCode() {
        return companyCode;
    }

    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    private String companyCode;

    public Date getAuditDate() {
        return auditDate;
    }

    public void setAuditDate(Date auditDate) {
        this.auditDate = auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_app.id
     *
     * @return the value of ele_app.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_app.id
     *
     * @param id the value for ele_app.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_app.name
     *
     * @return the value of ele_app.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_app.name
     *
     * @param name the value for ele_app.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_app.description
     *
     * @return the value of ele_app.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_app.description
     *
     * @param description the value for ele_app.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_app.imgUrl
     *
     * @return the value of ele_app.imgUrl
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_app.imgUrl
     *
     * @param imgUrl the value for ele_app.imgUrl
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_app.appUrl
     *
     * @return the value of ele_app.appUrl
     *
     * @mbggenerated
     */
    public String getAppUrl() {
        return appUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_app.appUrl
     *
     * @param appUrl the value for ele_app.appUrl
     *
     * @mbggenerated
     */
    public void setAppUrl(String appUrl) {
        this.appUrl = appUrl == null ? null : appUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_app.auditing
     *
     * @return the value of ele_app.auditing
     *
     * @mbggenerated
     */
    public Integer getAuditing() {
        return auditing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_app.auditing
     *
     * @param auditing the value for ele_app.auditing
     *
     * @mbggenerated
     */
    public void setAuditing(Integer auditing) {
        this.auditing = auditing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_app.auditUserId
     *
     * @return the value of ele_app.auditUserId
     *
     * @mbggenerated
     */
    public Integer getAuditUserId() {
        return auditUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_app.auditUserId
     *
     * @param auditUserId the value for ele_app.auditUserId
     *
     * @mbggenerated
     */
    public void setAuditUserId(Integer auditUserId) {
        this.auditUserId = auditUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_app.creator
     *
     * @return the value of ele_app.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_app.creator
     *
     * @param creator the value for ele_app.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_app.mofifor
     *
     * @return the value of ele_app.mofifor
     *
     * @mbggenerated
     */
    public Integer getMofifor() {
        return mofifor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_app.mofifor
     *
     * @param mofifor the value for ele_app.mofifor
     *
     * @mbggenerated
     */
    public void setMofifor(Integer mofifor) {
        this.mofifor = mofifor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_app.createTime
     *
     * @return the value of ele_app.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_app.createTime
     *
     * @param createTime the value for ele_app.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_app.motifyTime
     *
     * @return the value of ele_app.motifyTime
     *
     * @mbggenerated
     */
    public Date getMotifyTime() {
        return motifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_app.motifyTime
     *
     * @param motifyTime the value for ele_app.motifyTime
     *
     * @mbggenerated
     */
    public void setMotifyTime(Date motifyTime) {
        this.motifyTime = motifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_app.isDel
     *
     * @return the value of ele_app.isDel
     *
     * @mbggenerated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_app.isDel
     *
     * @param isDel the value for ele_app.isDel
     *
     * @mbggenerated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}