package com.eleapp.model;

import java.util.Date;

public class EleNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.publishDate
     *
     * @mbggenerated
     */
    private String publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.newsTypeId
     *
     * @mbggenerated
     */
    private Integer newsTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.keywords
     *
     * @mbggenerated
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.imgUrl
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.motifyTime
     *
     * @mbggenerated
     */
    private Date motifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.motifor
     *
     * @mbggenerated
     */
    private Integer motifor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.isDel
     *
     * @mbggenerated
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_news.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.id
     *
     * @return the value of ele_news.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.id
     *
     * @param id the value for ele_news.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.name
     *
     * @return the value of ele_news.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.name
     *
     * @param name the value for ele_news.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.publishDate
     *
     * @return the value of ele_news.publishDate
     *
     * @mbggenerated
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.publishDate
     *
     * @param publishDate the value for ele_news.publishDate
     *
     * @mbggenerated
     */
    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate == null ? null : publishDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.author
     *
     * @return the value of ele_news.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.author
     *
     * @param author the value for ele_news.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.newsTypeId
     *
     * @return the value of ele_news.newsTypeId
     *
     * @mbggenerated
     */
    public Integer getNewsTypeId() {
        return newsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.newsTypeId
     *
     * @param newsTypeId the value for ele_news.newsTypeId
     *
     * @mbggenerated
     */
    public void setNewsTypeId(Integer newsTypeId) {
        this.newsTypeId = newsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.keywords
     *
     * @return the value of ele_news.keywords
     *
     * @mbggenerated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.keywords
     *
     * @param keywords the value for ele_news.keywords
     *
     * @mbggenerated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.description
     *
     * @return the value of ele_news.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.description
     *
     * @param description the value for ele_news.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.imgUrl
     *
     * @return the value of ele_news.imgUrl
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.imgUrl
     *
     * @param imgUrl the value for ele_news.imgUrl
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.weight
     *
     * @return the value of ele_news.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.weight
     *
     * @param weight the value for ele_news.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.createTime
     *
     * @return the value of ele_news.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.createTime
     *
     * @param createTime the value for ele_news.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.motifyTime
     *
     * @return the value of ele_news.motifyTime
     *
     * @mbggenerated
     */
    public Date getMotifyTime() {
        return motifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.motifyTime
     *
     * @param motifyTime the value for ele_news.motifyTime
     *
     * @mbggenerated
     */
    public void setMotifyTime(Date motifyTime) {
        this.motifyTime = motifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.creator
     *
     * @return the value of ele_news.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.creator
     *
     * @param creator the value for ele_news.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.motifor
     *
     * @return the value of ele_news.motifor
     *
     * @mbggenerated
     */
    public Integer getMotifor() {
        return motifor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.motifor
     *
     * @param motifor the value for ele_news.motifor
     *
     * @mbggenerated
     */
    public void setMotifor(Integer motifor) {
        this.motifor = motifor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.isDel
     *
     * @return the value of ele_news.isDel
     *
     * @mbggenerated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.isDel
     *
     * @param isDel the value for ele_news.isDel
     *
     * @mbggenerated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_news.content
     *
     * @return the value of ele_news.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_news.content
     *
     * @param content the value for ele_news.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}