package com.eleapp.model;

import java.util.Date;

public class EleRbacOrganization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_rbac_organization.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_rbac_organization.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_rbac_organization.originalCode
     *
     * @mbggenerated
     */
    private String originalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_rbac_organization.firstSpell
     *
     * @mbggenerated
     */
    private String firstSpell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_rbac_organization.fullSpell
     *
     * @mbggenerated
     */
    private String fullSpell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_rbac_organization.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_rbac_organization.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_rbac_organization.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_rbac_organization.isDel
     *
     * @mbggenerated
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_rbac_organization.id
     *
     * @return the value of ele_rbac_organization.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_rbac_organization.id
     *
     * @param id the value for ele_rbac_organization.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_rbac_organization.name
     *
     * @return the value of ele_rbac_organization.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_rbac_organization.name
     *
     * @param name the value for ele_rbac_organization.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_rbac_organization.originalCode
     *
     * @return the value of ele_rbac_organization.originalCode
     *
     * @mbggenerated
     */
    public String getOriginalCode() {
        return originalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_rbac_organization.originalCode
     *
     * @param originalCode the value for ele_rbac_organization.originalCode
     *
     * @mbggenerated
     */
    public void setOriginalCode(String originalCode) {
        this.originalCode = originalCode == null ? null : originalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_rbac_organization.firstSpell
     *
     * @return the value of ele_rbac_organization.firstSpell
     *
     * @mbggenerated
     */
    public String getFirstSpell() {
        return firstSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_rbac_organization.firstSpell
     *
     * @param firstSpell the value for ele_rbac_organization.firstSpell
     *
     * @mbggenerated
     */
    public void setFirstSpell(String firstSpell) {
        this.firstSpell = firstSpell == null ? null : firstSpell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_rbac_organization.fullSpell
     *
     * @return the value of ele_rbac_organization.fullSpell
     *
     * @mbggenerated
     */
    public String getFullSpell() {
        return fullSpell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_rbac_organization.fullSpell
     *
     * @param fullSpell the value for ele_rbac_organization.fullSpell
     *
     * @mbggenerated
     */
    public void setFullSpell(String fullSpell) {
        this.fullSpell = fullSpell == null ? null : fullSpell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_rbac_organization.type
     *
     * @return the value of ele_rbac_organization.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_rbac_organization.type
     *
     * @param type the value for ele_rbac_organization.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_rbac_organization.createTime
     *
     * @return the value of ele_rbac_organization.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_rbac_organization.createTime
     *
     * @param createTime the value for ele_rbac_organization.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_rbac_organization.updateTime
     *
     * @return the value of ele_rbac_organization.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_rbac_organization.updateTime
     *
     * @param updateTime the value for ele_rbac_organization.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_rbac_organization.isDel
     *
     * @return the value of ele_rbac_organization.isDel
     *
     * @mbggenerated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_rbac_organization.isDel
     *
     * @param isDel the value for ele_rbac_organization.isDel
     *
     * @mbggenerated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}