package com.eleapp.model;

import java.util.Date;

public class EleSchool {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_school.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_school.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_school.province
     *
     * @mbggenerated
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_school.city
     *
     * @mbggenerated
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_school.county
     *
     * @mbggenerated
     */
    private Integer county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_school.rural
     *
     * @mbggenerated
     */
    private Long rural;

    public Long getRural() {
        return rural;
    }

    public void setRural(Long rural) {
        this.rural = rural;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_school.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_school.contactPerson
     *
     * @mbggenerated
     */
    private String contactPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_school.contactMobile
     *
     * @mbggenerated
     */
    private String contactMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_school.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_school.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_school.motifyTime
     *
     * @mbggenerated
     */
    private Date motifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_school.isDel
     *
     * @mbggenerated
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_school.id
     *
     * @return the value of ele_school.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_school.id
     *
     * @param id the value for ele_school.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_school.name
     *
     * @return the value of ele_school.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_school.name
     *
     * @param name the value for ele_school.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_school.province
     *
     * @return the value of ele_school.province
     *
     * @mbggenerated
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_school.province
     *
     * @param province the value for ele_school.province
     *
     * @mbggenerated
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_school.city
     *
     * @return the value of ele_school.city
     *
     * @mbggenerated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_school.city
     *
     * @param city the value for ele_school.city
     *
     * @mbggenerated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_school.county
     *
     * @return the value of ele_school.county
     *
     * @mbggenerated
     */
    public Integer getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_school.county
     *
     * @param county the value for ele_school.county
     *
     * @mbggenerated
     */
    public void setCounty(Integer county) {
        this.county = county;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_school.address
     *
     * @return the value of ele_school.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_school.address
     *
     * @param address the value for ele_school.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_school.contactPerson
     *
     * @return the value of ele_school.contactPerson
     *
     * @mbggenerated
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_school.contactPerson
     *
     * @param contactPerson the value for ele_school.contactPerson
     *
     * @mbggenerated
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_school.contactMobile
     *
     * @return the value of ele_school.contactMobile
     *
     * @mbggenerated
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_school.contactMobile
     *
     * @param contactMobile the value for ele_school.contactMobile
     *
     * @mbggenerated
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile == null ? null : contactMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_school.status
     *
     * @return the value of ele_school.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_school.status
     *
     * @param status the value for ele_school.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_school.createTime
     *
     * @return the value of ele_school.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_school.createTime
     *
     * @param createTime the value for ele_school.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_school.motifyTime
     *
     * @return the value of ele_school.motifyTime
     *
     * @mbggenerated
     */
    public Date getMotifyTime() {
        return motifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_school.motifyTime
     *
     * @param motifyTime the value for ele_school.motifyTime
     *
     * @mbggenerated
     */
    public void setMotifyTime(Date motifyTime) {
        this.motifyTime = motifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_school.isDel
     *
     * @return the value of ele_school.isDel
     *
     * @mbggenerated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_school.isDel
     *
     * @param isDel the value for ele_school.isDel
     *
     * @mbggenerated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}