package com.eleapp.model;

import java.util.Date;

public class EleTeacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.sertId
     *
     * @mbggenerated
     */
    private String sertId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.passWord
     *
     * @mbggenerated
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.subject
     *
     * @mbggenerated
     */
    private Integer subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.validatePwd
     *
     * @mbggenerated
     */
    private String validatePwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.birthYear
     *
     * @mbggenerated
     */
    private Integer birthYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.birthMonth
     *
     * @mbggenerated
     */
    private Integer birthMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.birthDay
     *
     * @mbggenerated
     */
    private Integer birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.imgUrl
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.createDate
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.motifyDate
     *
     * @mbggenerated
     */
    private Date motifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_teacher.isDel
     *
     * @mbggenerated
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.id
     *
     * @return the value of ele_teacher.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.id
     *
     * @param id the value for ele_teacher.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.name
     *
     * @return the value of ele_teacher.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.name
     *
     * @param name the value for ele_teacher.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.sertId
     *
     * @return the value of ele_teacher.sertId
     *
     * @mbggenerated
     */
    public String getSertId() {
        return sertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.sertId
     *
     * @param sertId the value for ele_teacher.sertId
     *
     * @mbggenerated
     */
    public void setSertId(String sertId) {
        this.sertId = sertId == null ? null : sertId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.passWord
     *
     * @return the value of ele_teacher.passWord
     *
     * @mbggenerated
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.passWord
     *
     * @param passWord the value for ele_teacher.passWord
     *
     * @mbggenerated
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.sex
     *
     * @return the value of ele_teacher.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.sex
     *
     * @param sex the value for ele_teacher.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.subject
     *
     * @return the value of ele_teacher.subject
     *
     * @mbggenerated
     */
    public Integer getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.subject
     *
     * @param subject the value for ele_teacher.subject
     *
     * @mbggenerated
     */
    public void setSubject(Integer subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.validatePwd
     *
     * @return the value of ele_teacher.validatePwd
     *
     * @mbggenerated
     */
    public String getValidatePwd() {
        return validatePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.validatePwd
     *
     * @param validatePwd the value for ele_teacher.validatePwd
     *
     * @mbggenerated
     */
    public void setValidatePwd(String validatePwd) {
        this.validatePwd = validatePwd == null ? null : validatePwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.mobile
     *
     * @return the value of ele_teacher.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.mobile
     *
     * @param mobile the value for ele_teacher.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.email
     *
     * @return the value of ele_teacher.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.email
     *
     * @param email the value for ele_teacher.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.birthYear
     *
     * @return the value of ele_teacher.birthYear
     *
     * @mbggenerated
     */
    public Integer getBirthYear() {
        return birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.birthYear
     *
     * @param birthYear the value for ele_teacher.birthYear
     *
     * @mbggenerated
     */
    public void setBirthYear(Integer birthYear) {
        this.birthYear = birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.birthMonth
     *
     * @return the value of ele_teacher.birthMonth
     *
     * @mbggenerated
     */
    public Integer getBirthMonth() {
        return birthMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.birthMonth
     *
     * @param birthMonth the value for ele_teacher.birthMonth
     *
     * @mbggenerated
     */
    public void setBirthMonth(Integer birthMonth) {
        this.birthMonth = birthMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.birthDay
     *
     * @return the value of ele_teacher.birthDay
     *
     * @mbggenerated
     */
    public Integer getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.birthDay
     *
     * @param birthDay the value for ele_teacher.birthDay
     *
     * @mbggenerated
     */
    public void setBirthDay(Integer birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.imgUrl
     *
     * @return the value of ele_teacher.imgUrl
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.imgUrl
     *
     * @param imgUrl the value for ele_teacher.imgUrl
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.createDate
     *
     * @return the value of ele_teacher.createDate
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.createDate
     *
     * @param createDate the value for ele_teacher.createDate
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.motifyDate
     *
     * @return the value of ele_teacher.motifyDate
     *
     * @mbggenerated
     */
    public Date getMotifyDate() {
        return motifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.motifyDate
     *
     * @param motifyDate the value for ele_teacher.motifyDate
     *
     * @mbggenerated
     */
    public void setMotifyDate(Date motifyDate) {
        this.motifyDate = motifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_teacher.isDel
     *
     * @return the value of ele_teacher.isDel
     *
     * @mbggenerated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_teacher.isDel
     *
     * @param isDel the value for ele_teacher.isDel
     *
     * @mbggenerated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}