package com.eleapp.model;

import java.util.Date;

public class EleWebSchoolcase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_web_schoolcase.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_web_schoolcase.appId
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_web_schoolcase.contect
     *
     * @mbggenerated
     */
    private String contect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_web_schoolcase.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_web_schoolcase.motifyTime
     *
     * @mbggenerated
     */
    private Date motifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ele_web_schoolcase.isDel
     *
     * @mbggenerated
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_web_schoolcase.id
     *
     * @return the value of ele_web_schoolcase.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_web_schoolcase.id
     *
     * @param id the value for ele_web_schoolcase.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_web_schoolcase.appId
     *
     * @return the value of ele_web_schoolcase.appId
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_web_schoolcase.appId
     *
     * @param appId the value for ele_web_schoolcase.appId
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_web_schoolcase.contect
     *
     * @return the value of ele_web_schoolcase.contect
     *
     * @mbggenerated
     */
    public String getContect() {
        return contect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_web_schoolcase.contect
     *
     * @param contect the value for ele_web_schoolcase.contect
     *
     * @mbggenerated
     */
    public void setContect(String contect) {
        this.contect = contect == null ? null : contect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_web_schoolcase.createTime
     *
     * @return the value of ele_web_schoolcase.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_web_schoolcase.createTime
     *
     * @param createTime the value for ele_web_schoolcase.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_web_schoolcase.motifyTime
     *
     * @return the value of ele_web_schoolcase.motifyTime
     *
     * @mbggenerated
     */
    public Date getMotifyTime() {
        return motifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_web_schoolcase.motifyTime
     *
     * @param motifyTime the value for ele_web_schoolcase.motifyTime
     *
     * @mbggenerated
     */
    public void setMotifyTime(Date motifyTime) {
        this.motifyTime = motifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ele_web_schoolcase.isDel
     *
     * @return the value of ele_web_schoolcase.isDel
     *
     * @mbggenerated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ele_web_schoolcase.isDel
     *
     * @param isDel the value for ele_web_schoolcase.isDel
     *
     * @mbggenerated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}