package com.eleapp.model;

import java.util.Date;

public class OauthAccessToken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.app_id
     *
     * @mbggenerated
     */
    private String app_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.access_token
     *
     * @mbggenerated
     */
    private String access_token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.user_code
     *
     * @mbggenerated
     */
    private String user_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.open_id
     *
     * @mbggenerated
     */
    private String open_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.create_date
     *
     * @mbggenerated
     */
    private Date create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.refresh_date
     *
     * @mbggenerated
     */
    private Date refresh_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.expires_in
     *
     * @mbggenerated
     */
    private Integer expires_in;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.id
     *
     * @return the value of oauth_access_token.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.id
     *
     * @param id the value for oauth_access_token.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.app_id
     *
     * @return the value of oauth_access_token.app_id
     *
     * @mbggenerated
     */
    public String getApp_id() {
        return app_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.app_id
     *
     * @param app_id the value for oauth_access_token.app_id
     *
     * @mbggenerated
     */
    public void setApp_id(String app_id) {
        this.app_id = app_id == null ? null : app_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.access_token
     *
     * @return the value of oauth_access_token.access_token
     *
     * @mbggenerated
     */
    public String getAccess_token() {
        return access_token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.access_token
     *
     * @param access_token the value for oauth_access_token.access_token
     *
     * @mbggenerated
     */
    public void setAccess_token(String access_token) {
        this.access_token = access_token == null ? null : access_token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.user_code
     *
     * @return the value of oauth_access_token.user_code
     *
     * @mbggenerated
     */
    public String getUser_code() {
        return user_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.user_code
     *
     * @param user_code the value for oauth_access_token.user_code
     *
     * @mbggenerated
     */
    public void setUser_code(String user_code) {
        this.user_code = user_code == null ? null : user_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.open_id
     *
     * @return the value of oauth_access_token.open_id
     *
     * @mbggenerated
     */
    public String getOpen_id() {
        return open_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.open_id
     *
     * @param open_id the value for oauth_access_token.open_id
     *
     * @mbggenerated
     */
    public void setOpen_id(String open_id) {
        this.open_id = open_id == null ? null : open_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.create_date
     *
     * @return the value of oauth_access_token.create_date
     *
     * @mbggenerated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.create_date
     *
     * @param create_date the value for oauth_access_token.create_date
     *
     * @mbggenerated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.refresh_date
     *
     * @return the value of oauth_access_token.refresh_date
     *
     * @mbggenerated
     */
    public Date getRefresh_date() {
        return refresh_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.refresh_date
     *
     * @param refresh_date the value for oauth_access_token.refresh_date
     *
     * @mbggenerated
     */
    public void setRefresh_date(Date refresh_date) {
        this.refresh_date = refresh_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.expires_in
     *
     * @return the value of oauth_access_token.expires_in
     *
     * @mbggenerated
     */
    public Integer getExpires_in() {
        return expires_in;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.expires_in
     *
     * @param expires_in the value for oauth_access_token.expires_in
     *
     * @mbggenerated
     */
    public void setExpires_in(Integer expires_in) {
        this.expires_in = expires_in;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.status
     *
     * @return the value of oauth_access_token.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.status
     *
     * @param status the value for oauth_access_token.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}