package com.eleapp.model;

public class SysRbacRoleauth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_roleauth.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_roleauth.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_roleauth.menuId
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_roleauth.buttons
     *
     * @mbggenerated
     */
    private String buttons;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_roleauth.id
     *
     * @return the value of sys_rbac_roleauth.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_roleauth.id
     *
     * @param id the value for sys_rbac_roleauth.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_roleauth.roleId
     *
     * @return the value of sys_rbac_roleauth.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_roleauth.roleId
     *
     * @param roleId the value for sys_rbac_roleauth.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_roleauth.menuId
     *
     * @return the value of sys_rbac_roleauth.menuId
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_roleauth.menuId
     *
     * @param menuId the value for sys_rbac_roleauth.menuId
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_roleauth.buttons
     *
     * @return the value of sys_rbac_roleauth.buttons
     *
     * @mbggenerated
     */
    public String getButtons() {
        return buttons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_roleauth.buttons
     *
     * @param buttons the value for sys_rbac_roleauth.buttons
     *
     * @mbggenerated
     */
    public void setButtons(String buttons) {
        this.buttons = buttons == null ? null : buttons.trim();
    }
}