package com.eleapp.model;

import java.util.Date;

public class SysRbacMenuChild {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_menu.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_menu.menuName
     *
     * @mbggenerated
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_menu.parentId
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_menu.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_menu.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_menu.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_menu.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_menu.isTop
     *
     * @mbggenerated
     */
    private String isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_menu.logo
     *
     * @mbggenerated
     */
    private String logo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_menu.id
     *
     * @return the value of sys_rbac_menu.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_menu.id
     *
     * @param id the value for sys_rbac_menu.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_menu.menuName
     *
     * @return the value of sys_rbac_menu.menuName
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_menu.menuName
     *
     * @param menuName the value for sys_rbac_menu.menuName
     *
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_menu.parentId
     *
     * @return the value of sys_rbac_menu.parentId
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_menu.parentId
     *
     * @param parentId the value for sys_rbac_menu.parentId
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_menu.url
     *
     * @return the value of sys_rbac_menu.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_menu.url
     *
     * @param url the value for sys_rbac_menu.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_menu.createTime
     *
     * @return the value of sys_rbac_menu.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_menu.createTime
     *
     * @param createTime the value for sys_rbac_menu.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_menu.updateTime
     *
     * @return the value of sys_rbac_menu.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_menu.updateTime
     *
     * @param updateTime the value for sys_rbac_menu.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_menu.status
     *
     * @return the value of sys_rbac_menu.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_menu.status
     *
     * @param status the value for sys_rbac_menu.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_menu.isTop
     *
     * @return the value of sys_rbac_menu.isTop
     *
     * @mbggenerated
     */
    public String getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_menu.isTop
     *
     * @param isTop the value for sys_rbac_menu.isTop
     *
     * @mbggenerated
     */
    public void setIsTop(String isTop) {
        this.isTop = isTop == null ? null : isTop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_menu.logo
     *
     * @return the value of sys_rbac_menu.logo
     *
     * @mbggenerated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_menu.logo
     *
     * @param logo the value for sys_rbac_menu.logo
     *
     * @mbggenerated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }
}