package com.eleapp.model;

public class SysRbacUserrole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_userrole.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_userrole.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rbac_userrole.roleId
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_userrole.id
     *
     * @return the value of sys_rbac_userrole.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_userrole.id
     *
     * @param id the value for sys_rbac_userrole.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_userrole.userId
     *
     * @return the value of sys_rbac_userrole.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_userrole.userId
     *
     * @param userId the value for sys_rbac_userrole.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rbac_userrole.roleId
     *
     * @return the value of sys_rbac_userrole.roleId
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rbac_userrole.roleId
     *
     * @param roleId the value for sys_rbac_userrole.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}