package com.eleapp.model;

import java.util.Date;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.AutoID
     *
     * @mbggenerated
     */
    private Integer autoID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.UserCode
     *
     * @mbggenerated
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.UserName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.PhoneNum
     *
     * @mbggenerated
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.PassWord
     *
     * @mbggenerated
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.NickName
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Integration
     *
     * @mbggenerated
     */
    private Double integration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.CreateDate
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.EMail
     *
     * @mbggenerated
     */
    private String EMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.UserType
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Friends
     *
     * @mbggenerated
     */
    private String friends;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.AutoID
     *
     * @return the value of userinfo.AutoID
     *
     * @mbggenerated
     */
    public Integer getAutoID() {
        return autoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.AutoID
     *
     * @param autoID the value for userinfo.AutoID
     *
     * @mbggenerated
     */
    public void setAutoID(Integer autoID) {
        this.autoID = autoID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.UserCode
     *
     * @return the value of userinfo.UserCode
     *
     * @mbggenerated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.UserCode
     *
     * @param userCode the value for userinfo.UserCode
     *
     * @mbggenerated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.UserName
     *
     * @return the value of userinfo.UserName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.UserName
     *
     * @param userName the value for userinfo.UserName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.PhoneNum
     *
     * @return the value of userinfo.PhoneNum
     *
     * @mbggenerated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.PhoneNum
     *
     * @param phoneNum the value for userinfo.PhoneNum
     *
     * @mbggenerated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.PassWord
     *
     * @return the value of userinfo.PassWord
     *
     * @mbggenerated
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.PassWord
     *
     * @param passWord the value for userinfo.PassWord
     *
     * @mbggenerated
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.NickName
     *
     * @return the value of userinfo.NickName
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.NickName
     *
     * @param nickName the value for userinfo.NickName
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Integration
     *
     * @return the value of userinfo.Integration
     *
     * @mbggenerated
     */
    public Double getIntegration() {
        return integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Integration
     *
     * @param integration the value for userinfo.Integration
     *
     * @mbggenerated
     */
    public void setIntegration(Double integration) {
        this.integration = integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.CreateDate
     *
     * @return the value of userinfo.CreateDate
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.CreateDate
     *
     * @param createDate the value for userinfo.CreateDate
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.EMail
     *
     * @return the value of userinfo.EMail
     *
     * @mbggenerated
     */
    public String getEMail() {
        return EMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.EMail
     *
     * @param EMail the value for userinfo.EMail
     *
     * @mbggenerated
     */
    public void setEMail(String EMail) {
        this.EMail = EMail == null ? null : EMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.UserType
     *
     * @return the value of userinfo.UserType
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.UserType
     *
     * @param userType the value for userinfo.UserType
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Status
     *
     * @return the value of userinfo.Status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Status
     *
     * @param status the value for userinfo.Status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.Friends
     *
     * @return the value of userinfo.Friends
     *
     * @mbggenerated
     */
    public String getFriends() {
        return friends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.Friends
     *
     * @param friends the value for userinfo.Friends
     *
     * @mbggenerated
     */
    public void setFriends(String friends) {
        this.friends = friends == null ? null : friends.trim();
    }
}